# Generated by Django 4.2.27 on 2025-12-31 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('UA', 'Ukraine'), ('PL', 'Poland'), ('RO', 'Romania'), ('SK', 'Slovakia'), ('MD', 'Moldova'), ('UK', 'United Kingdom')], default='UA', max_length=2)),
                ('org_type', models.CharField(choices=[('shelter', 'Animal Shelter'), ('vet', 'Veterinary Clinic'), ('transport', 'Transport Company')], default='shelter', max_length=20)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
